project/users/forms.py
from flask_wtf import FlaskForm
from wtforms import TextField, PasswordField
from wtforms.validators import DataRequired, Length, Email, EqualTo


class LoginForm(FlaskForm):
    username = TextField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators={DataRequired()})


class RegisterForm(FlaskForm):
    username = TextField(
        'username',
        validators=[DataRequired(), Length(min=3, max=25)]
    )
    email = TextField(
        'email',
        validators=[DataRequired(), Email(message=None), Length(min=6, max=40)]
    )
    password = PasswordField(
        'password',
        validators=[DataRequired(), Length(min=6, max=25)]
    )
    confirm = PasswordField(
        'Repeat password',
        validators=[
            DataRequired(), EqualTo('password', message='Passwords must match.')
        ]
    )

project/users/views.py
from flask import flash, redirect, render_template, request, \
    url_for, Blueprint, session  # pragma: no cover
from flask_login import login_user, login_required, logout_user  # pragma: no cover
from functools import wraps  # pragma: no cover

from .forms import LoginForm, RegisterForm  # pragma: no cover
from project import db  # pragma: no cover
from project.models import User, bcrypt  # pragma: no cover


################
#### config ####
################

users_blueprint = Blueprint(
    'users', __name__,
    template_folder='templates'
)   # pragma: no cover


###### Helper function #######
# login required decorator
# def login_required(f):
#     @wraps(f)
#     def wrap(*args, **kwargs):
#         if 'logged_in' in session:
#             return f(*args, **kwargs)
#         else:
#             flash("Unauthorized to access to this page, Please login", "danger")
#             return redirect(url_for('home.welcome'))
#     return wrap  # pragma: no cover

@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    error = None
    form = LoginForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            user = User.query.filter_by(name=request.form['username']).first()
            # print(user.name, user.password)
            if user is not None and \
                bcrypt.check_password_hash(user.password, request.form['password']):
                # session['logged_in'] = True
                login_user(user)
                flash("You are logged in", "success")
                return redirect(url_for('home.index'))
            else:
                error = 'Invalid login credentials, please try again!'
    return render_template('login.html', form=form, error=error)

@users_blueprint.route('/logout')
@login_required
def logout():
    # session.pop('logged_in', None)
    logout_user()
    flash("You are logged out", "warning")
    return redirect(url_for('home.welcome'))

@users_blueprint.route(
    '/register/', methods=['GET', 'POST'])   # pragma: no cover
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        user = User(
            name=form.username.data,
            email=form.email.data,
            password=form.password.data
        )
        db.session.add(user)
        db.session.commit()
        login_user(user)
        return redirect(url_for('home.index'))
    return render_template('register.html', form=form)

project/users/templates/login.html
{% extends 'base.html' %}
{% block content  %}

    <div class="row">
        <div class="col-md-8">

            <h1>Please login</h1>
            <form action="{{ url_for('users.login') }}" class="form-horizontal" method="post">
                <div class="form-group">
                    <label for="username" class="control-label sr-only">Username</label>
                    <input type="text" name="username" class="form-control" id="username" value="{{ request.form.username }}" placeholder="Username">
                </div>
                <div class="form-group">
                    <label for="password" class="control-label sr-only">Password</label>
                    <input type="password" name="password" class="form-control" id="password" value="{{ request.form.password }}" placeholder="Password">
                </div>
                <input type="submit" value="Login" class="btn btn-primary">
            </form>

        </div>
    </div>

{% endblock %}

project/users/templates/register.html
{% extends "base.html" %}

{% block content %}

<h1>Please Register</h1>
<hr>
<form class="form-signin" role="form" method="post" action="">
  {{ form.csrf_token }}
  <p>
    {{ form.username(placeholder="username") }}
    <span class="error">
      {% if form.username.errors %}
        {% for error in form.username.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <p>
  {{ form.email(placeholder="email") }}
    <span class="error">
      {% if form.email.errors %}
        {% for error in form.email.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <p>
  {{ form.password(placeholder="password") }}
    <span class="error">
      {% if form.password.errors %}
        {% for error in form.password.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <p>
  {{ form.confirm(placeholder="confirm") }}
    <span class="error">
      {% if form.confirm.errors %}
        {% for error in form.confirm.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <button class="btn btn-sm btn-success" type="submit">Register!</button>
</form>

{% endblock %}