project/home/forms.py
from flask_wtf import FlaskForm
from wtforms import TextField
from wtforms.validators import DataRequired, Length, Email, EqualTo


class MessageForm(FlaskForm):
    title = TextField('Title', validators=[DataRequired(), Length(min=6, max=40)])
    description = TextField('Description', validators={DataRequired(), Length(max=140)})

project/home/views.py
from flask import flash, url_for, render_template, redirect, session, \
    Blueprint, request  # pragma: no cover
from flask_login import login_required, current_user  # pragma: no cover
from functools import wraps  # pragma: no cover

from project import app, db  # pragma: no cover
from project.models import BlogPost  # pragma: no cover
from .forms import MessageForm  # pragma: no cover


################
#### config ####
################

home_blueprint = Blueprint(
    'home', __name__,
    template_folder='templates'
)   # pragma: no cover

###### Helper function #######
# login required decorator
# def login_required(f):
#     @wraps(f)
#     def wrap(*args, **kwargs):
#         if 'logged_in' in session:
#             return f(*args, **kwargs)
#         else:
#             flash("Unauthorized to access to this page, Please login", "danger")
#             return redirect(url_for('users.login'))
#     return wrap  # pragma: no cover


# use a route decorator to link function to a url
@home_blueprint.route('/', methods=['GET', 'POST'])
@login_required
def index():
    error = None
    form = MessageForm(request.form)
    if form.validate_on_submit():
        new_message = BlogPost(
            form.title.data,
            form.description.data,
            current_user.id
        )
        db.session.add(new_message)
        db.session.commit()
        flash('New entry was successfully posted. Thanks.', 'success')
        return redirect(url_for('home.index'))
    else:
        posts = db.session.query(BlogPost).all()
        return render_template(
            'index.html', posts=posts, form=form, error=error)

@home_blueprint.route('/welcome')
def welcome():
    return render_template('welcome.html')

project/users/views.py
from flask import flash, redirect, render_template, request, \
    url_for, Blueprint, session  # pragma: no cover
from flask_login import login_user, login_required, logout_user  # pragma: no cover
from functools import wraps  # pragma: no cover

from .forms import LoginForm, RegisterForm  # pragma: no cover
from project import db  # pragma: no cover
from project.models import User, bcrypt  # pragma: no cover


################
#### config ####
################

users_blueprint = Blueprint(
    'users', __name__,
    template_folder='templates'
)   # pragma: no cover


###### Helper function #######
# login required decorator
# def login_required(f):
#     @wraps(f)
#     def wrap(*args, **kwargs):
#         if 'logged_in' in session:
#             return f(*args, **kwargs)
#         else:
#             flash("Unauthorized to access to this page, Please login", "danger")
#             return redirect(url_for('home.welcome'))
#     return wrap  # pragma: no cover

@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    error = None
    form = LoginForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            user = User.query.filter_by(name=request.form['username']).first()
            # print(user.name, user.password)
            if user is not None and \
                bcrypt.check_password_hash(user.password, request.form['password']):
                # session['logged_in'] = True
                login_user(user)
                flash("You are logged in", "success")
                return redirect(url_for('home.index'))
            else:
                error = 'Invalid login credentials, please try again!'
    return render_template('login.html', form=form, error=error)

@users_blueprint.route('/logout')
@login_required
def logout():
    # session.pop('logged_in', None)
    logout_user()
    flash("You are logged out", "warning")
    return redirect(url_for('home.welcome'))

@users_blueprint.route(
    '/register/', methods=['GET', 'POST'])   # pragma: no cover
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        user = User(
            name=form.username.data,
            email=form.email.data,
            password=form.password.data
        )
        db.session.add(user)
        db.session.commit()
        login_user(user)
        return redirect(url_for('home.index'))
    return render_template('register.html', form=form)

project/home/templates/index.html
{% extends "base.html" %}
{% block content %}

<h1>Welcome to Flask!</h1>
<br>
<p>Click <a href="{{ url_for('users.logout') }}">here</a> to logout.</p>
<hr>

<!-- post form -->
<h3>Add a Post!</h3>
<hr>
<form class="form-message" role="form" method="post" action="/">
  {{ form.csrf_token }}
  <p>
    {{ form.title(placeholder="title") }}
    <span class="error">
      {% if form.title.errors %}
        {% for error in form.title.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <p>
  {{ form.description(placeholder="description") }}
    <span class="error">
      {% if form.description.errors %}
        {% for error in form.description.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <button class="btn btn-sm btn-success" type="submit">Post</button>
</form>
<hr>

<!-- All posts -->
<h3>Posts:</h3>
{% for post in posts %}
  <strong>Title:</strong> {{ post.title }} <br>
  <strong>Post:</strong> {{ post.description }} <br>
  <strong>Author:</strong> {{ post.author.name|capitalize }} <br>
<br>
{% endfor %}

{% endblock %}

project/home/templates/welcome.html
{% extends 'base.html' %}
{% block content  %}

    <h2>Welcome to Flask!</h2>
    <br>
    <p>Click <a href="{{ url_for('users.login') }}">here</a> to login.</p>

{% endblock %}